# Generated by Django 3.0.8 on 2020-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200801_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0, max_length=12)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
